Update new-deploy-adf.yml

diff --git a/.github/workflows/new-deploy-adf.yml b/.github/workflows/new-deploy-adf.yml
--- a/.github/workflows/new-deploy-adf.yml
+++ b/.github/workflows/new-deploy-adf.yml
@@ -24,12 +24,6 @@ jobs:
     steps:
       - name: Using ARM Template from source ADF instance
         run: echo "Source ADF instance is $SOURCE_ADF"
-
-      - name: Verify PrePostDeploymentScript exists
-        run: test -f ./PrePostDeploymentScript.Ver2.ps1 && echo "Script found" || (echo "Script missing" && exit 1)
-
-      - name: Verify ARMTemplateForFactory exists
-        run: test -f ./${{ env.SOURCE_ADF }}/ARMTemplateForFactory.json && echo "Script found" || (echo "Script missing" && exit 1)
   
       - name: Checkout adf_publish branch
         uses: actions/checkout@v3
@@ -44,6 +38,12 @@ jobs:
       # - name: List all files recursively
       #   run: find . -type f
 
+      - name: Verify PrePostDeploymentScript exists
+        run: test -f ./PrePostDeploymentScript.Ver2.ps1 && echo "Script found" || (echo "Script missing" && exit 1)
+
+      - name: Verify ARMTemplateForFactory exists
+        run: test -f ./${{ env.SOURCE_ADF }}/ARMTemplateForFactory.json && echo "Script found" || (echo "Script missing" && exit 1)
+        
       - name: Install Az PowerShell module
         run: Install-Module -Name Az.DataFactory -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
         shell: pwsh
